name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test || true
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-organization: ${{ secrets.SONAR_ORG }}
